### /notes

@BASE_URL = http://localhost
@PORT = 3100
@API = {{BASE_URL}}:{{PORT}}

### GET /healthy (health check)
GET {{API}}/healthy

### POST /notes (Add new member)
POST {{API}}/notes
Content-Type: application/json

{
    "title": "Example Note 05",
    "content": "Some random text.",
    "tags": ["test", "normal", "green"]
}

### GET /notes (Get all notes)
GET {{API}}/notes

### DELETE /notes/:noteId (Delete a member)
@noteId = 68ad7d52e94ea7036df4777f
DELETE  {{API}}/notes/{{noteId}}

### PUT /notes/:noteId (Update a member )
PUT  {{API}}/notes/{{noteId}}
Content-Type: application/json

{
    "title": "Example Note PUT 03",
    "content": "Some random text for PUT Testing.",
    "tags": ["test", "urgent", "red"]
}

### PATCH /notes/:noteId (Partially update a member)
PATCH  {{API}}/notes/{{noteId}}
Content-Type: application/json

{
    "title": "Example Note PATCH Testing 01"
}

### 404 Test - route does not exist
GET {{API}}/not-found-route

### 500 Test - force server error
# Example: POST without required fields (title & content missing)
GET {{API}}/error-test
