### /notes

@BASE_URL = http://localhost
@PORT = 3100
@API = {{BASE_URL}}:{{PORT}}

### GET /healthy (health check)
GET {{API}}/healthy

### POST /notes (Add new member)
POST {{API}}/notes
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTY0NTY0OTAsImV4cCI6MTc1NjQ2NzI5MH0.4zEgkFPOjuc0unTLG8zQNySBqNNvTPrML7YYoWiKEOg
Content-Type: application/json

{
    "title": "Example Note 03",
    "content": "Some random text.",
    "tags": ["test", "normal", "green"]
}

### GET /notes (Get all notes)
GET {{API}}/notes
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTY0NTY0OTAsImV4cCI6MTc1NjQ2NzI5MH0.4zEgkFPOjuc0unTLG8zQNySBqNNvTPrML7YYoWiKEOg
### DELETE /notes/:noteId (Delete a member)
@noteId = 68b168be83be487549a44f94
DELETE  {{API}}/notes/{{noteId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTY0NTY0OTAsImV4cCI6MTc1NjQ2NzI5MH0.4zEgkFPOjuc0unTLG8zQNySBqNNvTPrML7YYoWiKEOg

### PUT /notes/:noteId (Update a member )
PUT  {{API}}/notes/{{noteId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTY0NTY0OTAsImV4cCI6MTc1NjQ2NzI5MH0.4zEgkFPOjuc0unTLG8zQNySBqNNvTPrML7YYoWiKEOg
Content-Type: application/json

{
    "title": "Example Note PUT 02",
    "content": "Some random text for PUT Testing.",
    "tags": ["test", "urgent", "red"]
}

### PATCH /notes/:noteId (Partially update a member)
PATCH  {{API}}/notes/{{noteId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTY0NTY0OTAsImV4cCI6MTc1NjQ2NzI5MH0.4zEgkFPOjuc0unTLG8zQNySBqNNvTPrML7YYoWiKEOg
Content-Type: application/json

{
    "title": "Example Note PATCH Testing 01"
}

### 404 Test - route does not exist
GET {{API}}/not-found-route

### 500 Test - force server error
# Example: POST without required fields (title & content missing)
GET {{API}}/error-test
