### /notes

@BASE_URL = http://localhost
@PORT = 3100
@API = {{BASE_URL}}:{{PORT}}

### GET /healthy (health check)
GET {{API}}/healthy

### POST /notes (Add new member)
POST {{API}}/notes
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTc4MzkwNTcsImV4cCI6MTc1Nzg0OTg1N30.NVKPPqbwEo7tz12ymkaPKpmeEQqoaKmYGygEJT11qDY
Content-Type: application/json

{
    "title": "Example Note 106",
    "content": "Some random text.",
    "tags": [ "urgent", "green"]
}

### GET /notes (Get all notes)
GET {{API}}/notes
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTc4MzkwNTcsImV4cCI6MTc1Nzg0OTg1N30.NVKPPqbwEo7tz12ymkaPKpmeEQqoaKmYGygEJT11qDY
### DELETE /notes/:noteId (Delete a member)
@noteId = 68b168be83be487549a44f94
DELETE  {{API}}/notes/{{noteId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTc4MzkwNTcsImV4cCI6MTc1Nzg0OTg1N30.NVKPPqbwEo7tz12ymkaPKpmeEQqoaKmYGygEJT11qDY

### PUT /notes/:noteId (Update a member )
PUT  {{API}}/notes/{{noteId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTc4MzkwNTcsImV4cCI6MTc1Nzg0OTg1N30.NVKPPqbwEo7tz12ymkaPKpmeEQqoaKmYGygEJT11qDY
Content-Type: application/json

{
    "title": "Example Note PUT 02",
    "content": "Some random text for PUT Testing.",
    "tags": ["test", "urgent", "red"]
}

### PATCH /notes/:noteId (Partially update a member)
PATCH  {{API}}/notes/{{noteId}}
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIxNjYyNDAzZjcwNThhMzdiZGRmOWQiLCJpYXQiOjE3NTc4MzkwNTcsImV4cCI6MTc1Nzg0OTg1N30.NVKPPqbwEo7tz12ymkaPKpmeEQqoaKmYGygEJT11qDY
Content-Type: application/json

{
    "title": "Example Note PATCH Testing 01"
}

### 404 Test - route does not exist
GET {{API}}/not-found-route

### 500 Test - force server error
# Example: POST without required fields (title & content missing)
GET {{API}}/error-test
